export { EventsSlider } from './sliders/EventsSlider/EventsSlider';
export { NewsSlider } from './sliders/NewsSlider/NewsSlider';
export { RecommendationSlider } from './sliders/RecommendationSlider/RecSlider';
export { Button } from './Button/Button';
export { Navbar } from './Navbar/Navbar';
export { Footer } from './Footer/Footer';
export { Input } from './Input/Input';
export { PromoSlider } from './PromoSlider/PromoSlider';
export { MiniCards } from './MiniCards/MiniCards';
